name: GitHub Actions Demo
on: 
  push: 
    branches: [ master ]
  pull_request:
      branches: [ master ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: installing yarn
        run: yarn add
      - name: run build
        run: yarn build
      - name: run format
        run: yarn format
      - name: run lint
        run: yarn lint
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ This job's status is ${{ job.status }}."